'use client';

import { Check } from 'lucide-react';

import { Badge } from '@/shared/components/ui/badge';
import { Card } from '@/shared/components/ui/card';
import { Skeleton } from '@/shared/components/ui/skeleton';
import { CompareTask } from '@/shared/types/compare';

interface ModelCardProps {
  task: CompareTask;
  isSelected: boolean;
  onSelect: () => void;
  disabled?: boolean;
}

export function ModelCard({
  task,
  isSelected,
  onSelect,
  disabled,
}: ModelCardProps) {
  const isLoading = task.status === 'pending' || task.status === 'processing';
  const isFailed = task.status === 'failed';
  const isSuccess = task.status === 'success';

  return (
    <Card
      className={`
        relative overflow-hidden cursor-pointer transition-all duration-200
        ${isSelected ? 'ring-2 ring-primary ring-offset-2' : 'hover:ring-1 hover:ring-muted-foreground/20'}
        ${disabled ? 'opacity-50 cursor-not-allowed' : ''}
        ${isFailed ? 'opacity-60' : ''}
      `}
      onClick={() => !disabled && !isLoading && !isFailed && onSelect()}
    >
      {/* Header with model info */}
      <div className="flex items-center justify-between p-3 border-b bg-muted/30">
        <div className="flex items-center gap-2">
          <span className="font-medium text-sm">{task.modelLabel}</span>
          <Badge variant="secondary" className="text-xs">
            {task.modelStyle}
          </Badge>
        </div>
        {isSelected && (
          <div className="w-5 h-5 rounded-full bg-primary flex items-center justify-center">
            <Check className="w-3 h-3 text-primary-foreground" />
          </div>
        )}
      </div>

      {/* Image area */}
      <div className="aspect-square relative">
        {isLoading && (
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-2 bg-muted/50">
            <Skeleton className="w-full h-full absolute" />
            <div className="relative z-10 flex flex-col items-center gap-2">
              <div className="w-6 h-6 border-2 border-primary border-t-transparent rounded-full animate-spin" />
              <span className="text-xs text-muted-foreground">
                {task.status === 'pending' ? 'Queued...' : 'Generating...'}
              </span>
            </div>
          </div>
        )}

        {isFailed && (
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-2 bg-destructive/10">
            <span className="text-sm text-destructive">Failed</span>
            {task.error && (
              <span className="text-xs text-muted-foreground max-w-[80%] text-center">
                {task.error}
              </span>
            )}
          </div>
        )}

        {isSuccess && task.imageUrl && (
          <img
            src={task.imageUrl}
            alt={`Generated by ${task.modelLabel}`}
            className="w-full h-full object-cover"
            loading="lazy"
          />
        )}

        {isSuccess && !task.imageUrl && (
          <div className="absolute inset-0 flex items-center justify-center bg-muted">
            <span className="text-sm text-muted-foreground">No image</span>
          </div>
        )}
      </div>
    </Card>
  );
}
